version: "3.8"

services:
  database:
    build: ./database
    container_name: mysql_db
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend-network

  backend:
    build: ./backend
    container_name: node_backend
    restart: always
    env_file: .env
    depends_on:
      - database
    ports:
      - "3001:3001"
    networks:
      - frontend-network
      - backend-network

  frontend:
    build: ./frontend
    container_name: next_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - frontend-network

volumes:
  db_data:

networks:
  frontend-network:
  backend-network:
