name: Docker CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    # On injecte les secrets ici pour qu'ils soient dispos dans le terminal du CI
    env:
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: movies_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start services with Docker Compose
        run: |
          # On lance tout en arrière-plan
          docker-compose up -d

      - name: Wait for services to be healthy
        run: |
          # On attend que MySQL et le Backend soient prêts
          # Le backend met du temps car il attend MySQL (depends_on)
          echo "Waiting for services..."
          sleep 30 

      - name: Check Backend Logs (Debug)
        run: docker logs node_backend

      - name: Seed data via API
        run: |
          curl -X POST http://localhost:3001/films \
               -H "Content-Type: application/json" \
               -d '{"title": "Inception", "rating": 10}'

      - name: Test backend (should not be empty now)
        run: |
          RESPONSE=$(curl -s http://localhost:3001/films)
          echo "Response: $RESPONSE"
          if [ "$RESPONSE" == "[]" ]; then
            echo "Error: Database is empty!"
            exit 1
          fi

      - name: Test backend
        run: curl --fail http://localhost:3001/films || exit 1

      - name: Test frontend
        run: curl --fail http://localhost:3000 || exit 1

      - name: Stop services
        if: always()
        run: docker-compose down
